version: 2.1
commands:
  install_deps:
    description: Install dependencies
    steps:
      - run: bundle install
  rubocop:
    description: Run linter
    steps:
      - run: bundle exec rubocop --fail-level A
  tests:
    description: Run tests
    steps:
      - run: bundle exec rake test

jobs:
  build_2-6:
    docker:
      - image: cimg/ruby:2.6
    steps:
      - checkout
      - install_deps
      - rubocop
      - tests
  build_2-7:
    docker:
      - image: cimg/ruby:2.7
    steps:
      - checkout
      - install_deps
      - rubocop
      - tests

workflows:
  build_and_test:
    jobs:
      - build_2-6
      - build_2-7
