version: 2.1
commands:
  install_deps:
    steps:
      - run:
        command: bundle install
        name: Install Dependencies
  rubocop:
    steps:
      - run:
        command: bundle exec rubocop --fail-level A
        name: Linter
  tests:
    steps:
      - run:
        command: bundle exec rake test
        name: Run tests

jobs:
  build_2-6:
    docker:
      - image: cimg/ruby:2.6
    steps:
      - checkout
      - install_deps
      - rubocop
      - tests
  build_2-7:
    docker:
      - image: cimg/ruby:2.7
    steps:
      - checkout
      - install_deps
      - rubocop
      - tests

workflows:
  build_and_test:
    jobs:
      - build_2-6
      - build_2-7
